### ISSUE TITLE
Support for managing Apple Live Photos as a single item

### ISSUE THREAD

**Issue by rhymeswithmogul** [ubuntu/shotwell#11]
I use an iPhone, and when I take my pictures off the phone, I usually capture the entire Live Photo.  This is an Apple thing (introduced in iOS 9) that consists of two items with the same file name:

1. an image:  JPEG or HEIF, depending on device settings, and
2. a video:  in a QuickTime .MOV container, encoded with either H.264 or H.265, depending on device and/or device settings; not to exceed three seconds in length.
3. optionally, an edits file:  a plist file in XML format with a .AAE extension describing the edits done to the image so that they can be reversed at a later point.  This would only make sense to Apple devices and is not required for Shotwell, but I may as well mention that it may or may not exist, too.

For example, I might import IMG_0001.HEIC, IMG_0001.MOV, IMG_0002.HEIC, IMG_0002.MOV, and so on.

All my Live Photos are HEIC/H.265 so I can't test behavior at the moment with native files due to issue #8 blocking HEIF imports.  However, I converted one HEIC to JPEG and Shotwell treated them as two items.  I feel that Shotwell should recognize these two files as a single item and show them as one.

Adding support for viewing the photo and video, or even changing the photo to a different keyframe from the video (as you can do on iOS) would be an advanced feature that isn't totally necessary to have in Shotwell.  Just recognizing them as a single item would be good enough for library management, which is the most important thing.

**Comment by sergio-costas** [comment]
Mmm... I think that this should be proposed at upstream https://gitlab.gnome.org/GNOME/shotwell

**Comment by rhymeswithmogul** [comment]
Sorry, my mistake!

**Comment by sergio-costas** [comment]
No problem.
