### ISSUE TITLE
Ubuntu 22.04.3, snap version Shotwell 0.32.1 has not access to Camera

### ISSUE THREAD

**Issue by walter-ve** [ubuntu/shotwell#9]
the snap version of Shotwell has no access to my Camera.  'Normal' Shotwell works fine on same Ubuntu Installation.

It looks like permission error; I gave the snap version all permissions possible, but still it is not working.  
Permissions I added: read/write on removable storage devices, read system mount information and disk quotas, access hardware information (functionally last one seems not needed). some error message when running from terminal: `(shotwell:13580): libunity-CRITICAL **: 00:12:03.703: unity-inspector.vala:96: Unable to connect to session bus: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.256" (uid=1000 pid=13580 comm="/snap/shotwell/7/usr/bin/shotwell " label="snap.shotwell.shotwell (enforce)") interface="org.freedesktop.DBus" member="NameHasOwner" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (bus)` and when trying to import from the camera on a mounted drive: `(shotwell:13580): GLib-GIO-CRITICAL **: 00:13:09.049: g_file_new_for_uri: assertion 'uri != NULL' failed L 13580 2024-02-05 00:13:09 [CRT] app_dirs_is_in_import_dir: assertion 'G_TYPE_CHECK_INSTANCE_TYPE (file, g_file_get_type ())' failed`

Without Camera access, Shotwell I would call basically useless.

**Comment by walter-ve** [comment]
@sergio-costas how can test this fix?

Walter

**Comment by sergio-costas** [comment]
@walter-ve It seems that it hasn't been published yet... You have to download this repo, build the snap with "snapcraft -v", and install the .snap file.

**Comment by sergio-costas** [comment]
Oh, and connect all the plugs.

**Comment by walter-ve** [comment]
> Oh, and connect all the plugs.

Sorry; what do you mean with "all the plugs"?

**Comment by sergio-costas** [comment]
From a command line, run "sudo snap connect shotwell:XXX", with "XXX" being each one of the plugs that aren't connected.

**Comment by sergio-costas** [comment]
You can see which plugs aren't connected with "snap connections shotwell"
